### ISSUE TITLE
can't build mdb-jq-pro downgraded to 4.7.7

### ISSUE THREAD

**Issue by amery** [SpellCraft/mdb-boilerplate#9]
I'm a total rookie on the npm world. I just purchased mdb-pro, installed your boilerplate, installed mdb-pro, downgraded to 4.7.7 and BOOOM... hints? :(
```
npm run build

> mdb-boilerplate@3.0.0 build /home/amery/projects/cockroach.re/md-jq-pro-boilerplate
> webpack --mode production

/home/amery/projects/cockroach.re/md-jq-pro-boilerplate/node_modules/@xtuc/ieee754/index.js:1
(function (exports, require, module, __filename, __dirname) { export function read(buffer, offset, isLE, mLen, nBytes) {
                                                              ^^^^^^

SyntaxError: Unexpected token export
    at new Script (vm.js:83:7)
    at NativeCompileCache._moduleCompile (/home/amery/projects/cockroach.re/md-jq-pro-boilerplate/node_modules/v8-compile-cache/v8-compile-cache.js:240:18)
    at Module._compile (/home/amery/projects/cockroach.re/md-jq-pro-boilerplate/node_modules/v8-compile-cache/v8-compile-cache.js:186:36)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:770:10)
    at Module.load (internal/modules/cjs/loader.js:628:32)
    at Function.Module._load (internal/modules/cjs/loader.js:555:12)
    at Module.require (internal/modules/cjs/loader.js:666:19)
    at require (/home/amery/projects/cockroach.re/md-jq-pro-boilerplate/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at Object.<anonymous> (/home/amery/projects/cockroach.re/md-jq-pro-boilerplate/node_modules/@webassemblyjs/ieee754/lib/index.js:12:13)
    at Module._compile (/home/amery/projects/cockroach.re/md-jq-pro-boilerplate/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:770:10)
    at Module.load (internal/modules/cjs/loader.js:628:32)
    at Function.Module._load (internal/modules/cjs/loader.js:555:12)
    at Module.require (internal/modules/cjs/loader.js:666:19)
    at require (/home/amery/projects/cockroach.re/md-jq-pro-boilerplate/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at Object.<anonymous> (/home/amery/projects/cockroach.re/md-jq-pro-boilerplate/node_modules/@webassemblyjs/wasm-parser/lib/decoder.js:10:39)
    at Module._compile (/home/amery/projects/cockroach.re/md-jq-pro-boilerplate/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:770:10)
    at Module.load (internal/modules/cjs/loader.js:628:32)
    at Function.Module._load (internal/modules/cjs/loader.js:555:12)
    at Module.require (internal/modules/cjs/loader.js:666:19)
    at require (/home/amery/projects/cockroach.re/md-jq-pro-boilerplate/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at Object.<anonymous> (/home/amery/projects/cockroach.re/md-jq-pro-boilerplate/node_modules/@webassemblyjs/wasm-parser/lib/index.js:8:39)
    at Module._compile (/home/amery/projects/cockroach.re/md-jq-pro-boilerplate/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:770:10)
    at Module.load (internal/modules/cjs/loader.js:628:32)
    at Function.Module._load (internal/modules/cjs/loader.js:555:12)
    at Module.require (internal/modules/cjs/loader.js:666:19)
    at require (/home/amery/projects/cockroach.re/md-jq-pro-boilerplate/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at Object.<anonymous> (/home/amery/projects/cockroach.re/md-jq-pro-boilerplate/node_modules/webpack/lib/wasm/WebAssemblyParser.js:8:20)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mdb-boilerplate@3.0.0 build: `webpack --mode production`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the mdb-boilerplate@3.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/amery/.npm/_logs/2019-05-17T16_23_30_490Z-debug.log
```

**Comment by amery** [comment]
I tried from zero again. `npm run build` first failed because _acron_ was missing, and then because of this _export_.

I guess I should start from zero again and see if it works at all *before* installing _pro_
```
npm run build

> mdb-boilerplate@3.0.0 build /home/amery/projects/cockroach.re/md-jq-pro-boilerplate
> webpack --mode production

/home/amery/projects/cockroach.re/md-jq-pro-boilerplate/node_modules/webpack-cli/bin/cli.js:74
				throw err;
				^

Error: Cannot find module '/home/amery/projects/cockroach.re/md-jq-pro-boilerplate/node_modules/acorn/dist/acorn.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (internal/modules/cjs/loader.js:227:19)
    at Function.Module._findPath (internal/modules/cjs/loader.js:364:18)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:597:27)
    at Function.Module._load (internal/modules/cjs/loader.js:526:27)
    at Module.require (internal/modules/cjs/loader.js:666:19)
    at require (/home/amery/projects/cockroach.re/md-jq-pro-boilerplate/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at Object.<anonymous> (/home/amery/projects/cockroach.re/md-jq-pro-boilerplate/node_modules/webpack/lib/Parser.js:9:15)
    at Module._compile (/home/amery/projects/cockroach.re/md-jq-pro-boilerplate/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:770:10)
    at Module.load (internal/modules/cjs/loader.js:628:32)
    at Function.Module._load (internal/modules/cjs/loader.js:555:12)
    at Module.require (internal/modules/cjs/loader.js:666:19)
    at require (/home/amery/projects/cockroach.re/md-jq-pro-boilerplate/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at Object.<anonymous> (/home/amery/projects/cockroach.re/md-jq-pro-boilerplate/node_modules/webpack/lib/JavascriptModulesPlugin.js:7:16)
    at Module._compile (/home/amery/projects/cockroach.re/md-jq-pro-boilerplate/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:770:10)
    at Module.load (internal/modules/cjs/loader.js:628:32)
    at Function.Module._load (internal/modules/cjs/loader.js:555:12)
    at Module.require (internal/modules/cjs/loader.js:666:19)
    at require (/home/amery/projects/cockroach.re/md-jq-pro-boilerplate/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at Object.<anonymous> (/home/amery/projects/cockroach.re/md-jq-pro-boilerplate/node_modules/webpack/lib/WebpackOptionsApply.js:9:33)
    at Module._compile (/home/amery/projects/cockroach.re/md-jq-pro-boilerplate/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:770:10)
    at Module.load (internal/modules/cjs/loader.js:628:32)
    at Function.Module._load (internal/modules/cjs/loader.js:555:12)
    at Module.require (internal/modules/cjs/loader.js:666:19)
    at require (/home/amery/projects/cockroach.re/md-jq-pro-boilerplate/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at Object.<anonymous> (/home/amery/projects/cockroach.re/md-jq-pro-boilerplate/node_modules/webpack/lib/webpack.js:10:29)
    at Module._compile (/home/amery/projects/cockroach.re/md-jq-pro-boilerplate/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:770:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mdb-boilerplate@3.0.0 build: `webpack --mode production`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the mdb-boilerplate@3.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/amery/.npm/_logs/2019-05-17T16_46_04_848Z-debug.log
```

**Comment by amery** [comment]
well.... it happens out of the box :(

**Comment by amery** [comment]
downgrading `webpack-cli` to 3.1.2 didn't help either

**Comment by SpellCraft** [comment]
That's mighty weird. Did you follow the steps to uninstall the free version of MDB, generating a token and installing the pro version of MDB?

**Comment by SpellCraft** [comment]
Just did a quick test on one of my Windows machines. Here's the log from Powershell:
https://gist.github.com/SpellCraft/4a5dbf5456d021fd2db948f44cc6eb6d

And screenshots of the corresponding changed files from the log:
https://i.imgur.com/P1jZLwK.png
https://i.imgur.com/87sOGtd.png
(You have to manually edit the paths for now)

**Comment by SpellCraft** [comment]
I've been travelling to a new work place so I've been unable to reach out; I'll take a look today at the main repo why it's acting up. It's weird that node_modules of other packages fail to export or be installed properly so might just have been a one off bug.

I assume you're using the latest or current LTE version of NodeJs?

**Comment by amery** [comment]
> I assume you're using the latest or current LTE version of NodeJs?

```
$ npm --version
6.9.0
```

**Comment by amery** [comment]
not strictly connected to this issue but 4.8.2 works fine.... if the first `npm i` is an mdb package. if `node_modules` is populated by `npm i` or `npm i npm-check-updates` before installing the mdb pro packages the webpack issue still happens.

**Comment by SpellCraft** [comment]
Pushed a new update to the repository, updating some packages as well as MDB to the latest versions. I can't find any more issues with MDB and this repository. :)
